spring:
  profiles:
    active: default,local
  application:
    name: eureka
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
server:
  port: 11000
