logging:
  level:
    com:
      netflix:
        eureka: ERROR
        discovery: ERROR
eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:11000/eureka/
server:
  port: 11000