eureka:
  instance:
    hostname: criprj
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://criprj:8080/eureka/
server:
  port: 8080