eureka:
  instance:
    hostname: criprj
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://criprj:11000/
server:
  port: 11000